import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import VideoPlay from '../src/componetes/videoPlay'


const Home = () => {

  const [hasWindow, setHasWindow] = useState(false);
  useEffect(() => {
    if (typeof window !== "undefined") {
      setHasWindow(true);
    }
  }, []);



  //loop={true} 
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>test video</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {/*  <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}


          {hasWindow && <VideoPlay />}

        </main>


      </div>

    </>
  )
}

export default Home;